--- 
title: "Hakai Institute R Data-Analyst Guide"
author: "Brett Johnson"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: br-johnson/Hakai-Data-Analyst
description: "A guideline for R analysts; getting started, best practices, and collaboration"
---
# Introduction
```{r, include=FALSE}
# Type the command below into the update the viewer auto
#bookdown::serve_book(dir = ".", output_dir = "_book", preview = TRUE, in_session = TRUE)
```

The objective of this guide is to serve as a:

1) Reference guide for the new R Analyst; 
2) best-practice guidelines for Hakai staff to make reproducible analyses, and use literate programming methods in R-Studio; and 
3) a guide to enhance collaborative capacities for ecological analyses within and between Hakai research programs and generally the science community using Git and GitHub. 

My hope is this guide will teach you a logical methodology that results in; high analytical quality, reproducible research methods, open science practices, and facilitates collaboration. The beginning of this guide may seem difficult, but in making this guide I've kept long-term goals in mind and in a sense I have front-loaded the R learning experience with important concepts that will serve you in the near future and in the long-run.

## Acknowledgements
Much of this document simply refers you to material that others have worked very hard to make simple. I simply point to these resources in an order that makes sense to me and forms a systematic approach. Many thanks to the following people for making this possible:

* Dr. Jenny Bryan, UBC Professor in the Masters of Data Science Program. [Twitter](https://twitter.com/JennyBryan), [GitHUB](https://github.com/jennybc).
* Dr. Roger Peng, Professor of Biostatistics at Johns Hopkins University. [Website](http://www.biostat.jhsph.edu/~rpeng/), [GitHUB](https://github.com/rdpeng).
* Dr. Hadley Wickham, Chief Scientists at R-Studio. [Website](http://hadley.nz/), [Twitter](https://twitter.com/hadleywickham), [GitHUB](https://github.com/hadley).

