# Reference Guide for the New R Analyst

## Set-up GitHUB

The reason this document is hosted on GitHUB is that we'll be working with GitHUB throughout this guide and throughout your own analyses.  If you're interested in learning why you should use git, read [Chapter 1; 'Why Git? Why GitHUB' from Jenny Bryans Book](http://happygitwithr.com/big-picture.html#why-git). Otherwise take my word for it and we can get this part out of the way before we move on to learning R.

First, you're going to want to [sign up for a GitHUB account](https://github.com)

Now that you have a GitHUB account, you should introduce yourself and let me know you're going to work through this material. To do that go to the issues tab in this repository (repo) and 'create a new issue' and type a message to introduce yourself. Using issues is also a great way to ask questions about course material.

Next, you should fork this repo so that you can access this document from your GitHUB profile, edit it, and make a 'pull request' to suggest edits to me. This serves two purposes: 1) the quality of this guide will be improved if you take time to edit chapters and contribute your insights on what didn't work for you; and 2) forking repos and making pull-requests is training you for the workflow you will use when contributing to colleagues' analyses in the very near future. 

To successfully fork this repo and suggest edits simply go to [my repo here](https://github.com/Br-Johnson/Hakai-Data-Analyst) and click on the name of this chapter: 'new_analysts.Rmd', once it's open click on the pencil icon to suggest edits. Editing automcatically forks the repo and makes a copy in your own list of repos. Now you can make all the edits you'd like and when your happy you can click on 'pull request' to send the updates back to me so I can review them and decide if I should accept your edits and merge them.

If you  aren't successfull forking my repo, read [Chapter 24 of Jenny Brians Book; 'Fork a Repo'](http://happygitwithr.com/fork.html).

You'll notice that this file is a '.Rmd' file which stands for R  Markdown. [Read this](https://guides.github.com/features/mastering-markdown/) if you're interested in markdown syntax, otherwise come back to it later.

#### GitHUB Checklist
Complete these items before moving on to the next section.

1) Create a GitHUB account
2) Create a new 'issue' to introduce yourself or ask a question
3) Fork this repository
4) Make a pull request to suggest an edit or update to this guide

## Install and Set up R and R Studio

R is the statistical programming language that R Studio understands. I think of R Studio as being the front-end user interface to the coding language R which is running in the background. For this all to work you you need to download two files to start; R and R Studio.

1) Watch my [Youtube Video](https://youtu.be/G3kaguwW8yc) on how to install R and R Studio
2) Go to https://cran.r-project.org/ and follow the link to the download for your operating system.
3) Go to https://www.rstudio.com/products/rstudio/download/ to download R studio

## Install and set-up Git
Next you're going to install Git. Git tracks the changes you make in R-Studio locally and upon your request, pushes changes to your remote repository at GitHUB. Similar to the relationship between R and R-Studio, Git is the *local* version control system running in the back ground on your computer while GitHUB is the *remote* user interface for saving, tracking, and sharing updated versions of your analyses that is hosted on a remote server. 

Installing Git locally and getting Git to communicate to your remote GitHUB website account, and then getting them to talk with RStudio takes a number of steps to complete...This next part can be painful to work through, but it is 100 % neccesary and well worth it in the long-run.

1) Install Git and GitHUB and get them talking to R-Studio using [Jenny Bryan's Guide](http://happygitwithr.com/install-git.html), start at chapter 7 and work to the end of chapter 13.
2) If you're successful: Thank god that's over. Otherwise continue on to Chapter 14 and 15 if you're having problems.

Congratulations you now have setup the three main tools in the R Analyst toolbox: R, R Studio and GitHUB.

## Familiarize yourself with R and R-Studio
Now that you have the tools you need, lets get familiar with R-Studio and the R programming language.

Lets install you're first package in R-Studio. You can think of packages as extensions to R. Because R is open-source, people often write packages to make different functions, features, or analyses possible. 

Your first package will be swirl(). swirl() is a package for learning (and teaching) statistics and R simultaneously and interactively.

Watch [this youtube video](https://youtu.be/0eiOi5i34rs) to install your first package and start learning R with the swirl() package. 

## Learning Objectives:
There are a plethora of resources to help you learn R. After a year and a half of sifting through this material and learning R myself I've found these resources to be the best, and I present them to you in an order I wish I had learned them in. Together these objectives direct you through an efficient way to learn R, and combined with a graduate level understanding of statistics you should gain an intermediate skill level in R using a very high-level, and modern approach.

1) Complete chapter 1 in swirl()

2) Next, watch [this R-Studio Tutorial](https://www.rstudio.com/resources/webinars/rstudio-essentials-webinar-series-part-1/). Skip over the sections related to the Server Pro version of R-Studio.

3) Start making some awesome graphs by working through [section 3.1 to 3.5 in Hadley Wickham's R for Data Science Book](http://r4ds.had.co.nz/data-visualisation.html)

4) Complete chapters 2 – 7 in swirl() inside of RStudio. If you have questions about the topics covered in these swirl chapters, consult Roger Peng's Book [R Programming](https://bookdown.org/rdpeng/rprogdatascience/)

5) Watch R-Studio tutorial: [Projects and R Studio](https://www.rstudio.com/resources/webinars/rstudio-essentials-webinar-series-managing-change-part-1/)

6) Commplete the remaining chapters in the swirl() R Programming course, and try some of the other swirl courses that interest you.

7) Read [Chapter 7 of Jenny Bryans Book](http://happygitwithr.com/new-github-first.html) to get your own project set up on GitHUB first and then in R-Studio so you can start experimenting with your own data set and your own analysis. 

8) Read from front to back Hadley Wickam and Garrett Grolemund's Book: [R For Data Science](http://r4ds.had.co.nz/) to master the 'tidyverse'; a deadly combination of packages and a well thought out and systematic approach to "import, tidy, transform, visualize, and model data." Using the tidyverse as a foundation for your coding replaces the 'million and 1 ways' of doing things in R into a concise, grammar of data analysis programming.

All these learning objectives will take some time to complete, and you will be very frustrated at points but know that we all have suffered through this initial learning curve and eventually it gets easier. If you manage to complete all of these requirements you are well on your way to becoming an intermediate R programmer

## The Process of Data Analysis
Roger Peng puts it simplest:
* Define the question
* Define the ideal data set
* Determine what data you can access
* Obtain the data
* Clean the data
* Exploratory data analysis
* Statistical prediction/modeling
* Interpret results
* Challenge results
* Synthesize/write up results
* Create reproducible code
