# Guidelines for Hakai Data Analysts
## Programming Style Guide
[Google's R Style Guide](https://google.github.io/styleguide/Rguide.xml) is an excellent place to start. Googles guide recommendeds two space indents for new lines of code within the same function, but I prefer 8. See [Roger Pengs Coding Standards Video](https://www.youtube.com/watch?v=MSPKE1y3cyQ) for some excellent suggestions that I mostly adhere to.

## Organization of a Data Analysis Workflow
I keep all files associated with an analysis in a google drive folder, so that I can give collaborators access to RAW data so they can work with it directly.

I use a default folder structure for every analysis based on the files that are typically produced from every analysis. First I create a folder for the name of the project and create these sub-folders within the project folder.

The sub folders I use are: 
* raw data
* processed data 
* raw scripts
* final scripts
* exploratory figures
* final figures
* notebook

I typically have my notebook folder set as my working directory and navigate from there to save figures, processed data etc. using the "../processed data/yourfilename.csv". The .. before the forward slash tells R to navigate up one level from your working directory, and then down one level into, in this case, your processed data folder.

## Reproducible Research, Literate Programming, and the Open Notebook
These three concepts bring together a very modern way of conducting science. These are the benefits of using these methods:

* They save you work in the long run by being able to reproduce your own analyses after you've long forgotten the details of how they were conducted
* If you weave a narrative text into your computer code you'll be able to understand what you were thinking at a later time when you revisit it.
* You can easily collaborate 
* show your peers that you have nothing to hide in your analytical methods
* that you are willing to share your analyses in hopes that others will improve the quality of your analysis by offering their insight.


Watch:
* [Dr. RD Peng's youtube video](https://www.youtube.com/watch?v=DfBSiOupI1I) on reproducible research.
* As well as his video on [Literate Programming](https://www.youtube.com/watch?v=YcJb1HBc-1Q)
* [Open notebook science](https://en.wikipedia.org/wiki/Open_notebook_science) involves providing all of your research thoughts and ideas from within your notebook for maximum transparacey.
 
## Reproducible research using markdown, notebooks, or other (Need significant additions, editing, and contributions beyond here)

R Notebooks is a good way to collaborate with other analysts. When using R Notebooks it's best to set defualts to:
You want your YAML header to look something like this:
`output:
  html_notebook: default, 
  keep_md: TRUE
  github_document: default`

## Collaboration with Phyton users
The data analysis files you commit to your repo should include a 'feather' table. [Feather](https://blog.rstudio.org/2016/03/29/feather/) is data frame format that is readable by both Python and R, and therefore every analysis should produce this type of dataframe to ensure reproducibility for Python users
